version: "3.8"

services:
    mysqldb:
      image: mysql:latest
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      volumes:
        - ./init:/docker-entrypoint-initdb.d
        - mysqlVolume:/var/lib/mysql
        - mysqlConfig:/etc/mysql
      ports:
        - "3306:3306"
    docker-python:
      build:
          context: .
      ports:
          - "3000:5000"
      depends_on:
          - mysqldb
          
volumes:
      mysqlVolume:
      mysqlConfig:

